name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Zip the build output
      run: |
        mkdir build-zip
        zip -r build-zip/build.zip dist/

    - name: Create Release and Upload Asset
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build-zip/build.zip"
        token: ${{ secrets.TOKEN }}
        tag: ${{ github.ref }}
        name: Release ${{ github.ref }}
        allowUpdates: true
